import { Unit, VisitorPass, VisitorLog, ParkingSpace, LPRDetection } from './types';

export const initialUnits: Unit[] = [
  {
    id: 'u-101',
    unitNumber: 'A-101',
    block: 'Tower A',
    floor: 1,
    residentName: 'Sarah Jenkins',
    residentPhone: '+1 (555) 234-5678',
    status: 'ExpectingGuest',
    allocatedParkingBay: 'R-101',
    registeredVehicles: ['SJK-8821', 'SJK-1102'],
  },
  {
    id: 'u-102',
    unitNumber: 'A-102',
    block: 'Tower A',
    floor: 1,
    residentName: 'David Chen',
    residentPhone: '+1 (555) 876-5432',
    status: 'Occupied',
    allocatedParkingBay: 'R-102',
    registeredVehicles: ['DC-9921'],
  },
  {
    id: 'u-205',
    unitNumber: 'A-205',
    block: 'Tower A',
    floor: 2,
    residentName: 'Marcus Vance',
    residentPhone: '+1 (555) 443-2211',
    status: 'ExpectingGuest',
    allocatedParkingBay: 'R-205',
    registeredVehicles: ['MV-7740'],
  },
  {
    id: 'u-304',
    unitNumber: 'B-304',
    block: 'Tower B',
    floor: 3,
    residentName: 'Elena Rostova',
    residentPhone: '+1 (555) 998-1122',
    status: 'Occupied',
    allocatedParkingBay: 'R-304',
    registeredVehicles: ['ER-3390'],
  },
  {
    id: 'u-410',
    unitNumber: 'B-410',
    block: 'Tower B',
    floor: 4,
    residentName: 'Dr. Robert Thorne',
    residentPhone: '+1 (555) 332-9988',
    status: 'Vacant',
    allocatedParkingBay: 'R-410',
    registeredVehicles: [],
  },
  {
    id: 'u-501',
    unitNumber: 'B-501 (Penthouse)',
    block: 'Tower B',
    floor: 5,
    residentName: 'Alex & Maria Sterling',
    residentPhone: '+1 (555) 111-2233',
    status: 'ExpectingGuest',
    allocatedParkingBay: 'R-501',
    registeredVehicles: ['STERLING-1'],
  },
];

export const initialVisitorPasses: VisitorPass[] = [
  {
    id: 'vp-8942',
    passCode: 'QR-89421',
    guestName: 'Liam Harrison',
    guestPhone: '+1 (555) 667-8899',
    vehiclePlate: 'LHM-4491',
    unitId: 'u-101',
    unitNumber: 'A-101',
    residentName: 'Sarah Jenkins',
    visitorType: 'Guest',
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 86400000).toISOString(),
    status: 'Active',
    assignedParkingBay: 'V-03',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'vp-9102',
    passCode: 'QR-91022',
    guestName: 'FedEx Express (Driver: Mike)',
    guestPhone: '+1 (555) 888-0000',
    vehiclePlate: 'FDX-998',
    unitId: 'u-205',
    unitNumber: 'A-205',
    residentName: 'Marcus Vance',
    visitorType: 'Delivery',
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 14400000).toISOString(),
    status: 'Active',
    assignedParkingBay: 'V-01',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'vp-7721',
    passCode: 'QR-77215',
    guestName: 'Apex Plumbing Services',
    guestPhone: '+1 (555) 444-5555',
    vehiclePlate: 'PLUMB-9',
    unitId: 'u-501',
    unitNumber: 'B-501 (Penthouse)',
    residentName: 'Alex Sterling',
    visitorType: 'Contractor',
    validFrom: new Date().toISOString(),
    validUntil: new Date(Date.now() + 28800000).toISOString(),
    status: 'Active',
    assignedParkingBay: 'V-08',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
];

export const initialVisitorLogs: VisitorLog[] = [
  {
    id: 'vl-001',
    guestName: 'Jonathan Reed',
    visitorType: 'Guest',
    unitNumber: 'A-102',
    vehiclePlate: 'JRD-1092',
    entryTime: new Date(Date.now() - 7200000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    guardName: 'Officer Miller',
    assignedParkingBay: 'V-04',
    status: 'Inside',
    notes: 'Visiting for dinner',
  },
  {
    id: 'vl-002',
    guestName: 'Amazon Logistics',
    visitorType: 'Delivery',
    unitNumber: 'B-304',
    vehiclePlate: 'AMZ-5501',
    entryTime: new Date(Date.now() - 3600000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    exitTime: new Date(Date.now() - 1800000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    guardName: 'Officer Miller',
    assignedParkingBay: 'V-01',
    status: 'Departed',
    notes: 'Dropped off packages at lobby',
  },
  {
    id: 'vl-003',
    guestName: 'Chloe Bennett',
    visitorType: 'Guest',
    unitNumber: 'A-205',
    vehiclePlate: 'CHL-778',
    entryTime: new Date(Date.now() - 18000000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    guardName: 'Officer Miller',
    assignedParkingBay: 'V-02',
    status: 'Inside',
    notes: 'Overstay Warning: >4 hours parked',
  },
];

export const initialParkingSpaces: ParkingSpace[] = [
  { id: 'ps-v01', bayNumber: 'V-01', zone: 'Zone B1 (Visitor)', type: 'Visitor', status: 'Available' },
  { id: 'ps-v02', bayNumber: 'V-02', zone: 'Zone B1 (Visitor)', type: 'Visitor', status: 'Overstay_Warning', currentVehiclePlate: 'CHL-778', assignedUnitNumber: 'A-205', occupantName: 'Chloe Bennett', entryTime: '4h 15m ago', maxHoursAllowed: 4 },
  { id: 'ps-v03', bayNumber: 'V-03', zone: 'Zone B1 (Visitor)', type: 'Visitor', status: 'Reserved', assignedUnitNumber: 'A-101', occupantName: 'Reserved for Liam Harrison (QR-89421)' },
  { id: 'ps-v04', bayNumber: 'V-04', zone: 'Zone B1 (Visitor)', type: 'Visitor', status: 'Occupied_Visitor', currentVehiclePlate: 'JRD-1092', assignedUnitNumber: 'A-102', occupantName: 'Jonathan Reed', entryTime: '2h ago' },
  { id: 'ps-v05', bayNumber: 'V-05', zone: 'Zone B1 (Visitor)', type: 'EV_Charging', status: 'Available' },
  { id: 'ps-v06', bayNumber: 'V-06', zone: 'Zone B1 (Visitor)', type: 'EV_Charging', status: 'Available' },
  { id: 'ps-v07', bayNumber: 'V-07', zone: 'Zone B1 (Visitor)', type: 'Handicap', status: 'Available' },
  { id: 'ps-v08', bayNumber: 'V-08', zone: 'Zone B1 (Visitor)', type: 'Visitor', status: 'Reserved', assignedUnitNumber: 'B-501', occupantName: 'Reserved for Apex Plumbing' },

  { id: 'ps-r101', bayNumber: 'R-101', zone: 'Zone B2 (Resident)', type: 'Resident', status: 'Occupied_Resident', currentVehiclePlate: 'SJK-8821', assignedUnitNumber: 'A-101', occupantName: 'Sarah Jenkins' },
  { id: 'ps-r102', bayNumber: 'R-102', zone: 'Zone B2 (Resident)', type: 'Resident', status: 'Occupied_Resident', currentVehiclePlate: 'DC-9921', assignedUnitNumber: 'A-102', occupantName: 'David Chen' },
  { id: 'ps-r205', bayNumber: 'R-205', zone: 'Zone B2 (Resident)', type: 'Resident', status: 'Available', assignedUnitNumber: 'A-205', occupantName: 'Marcus Vance' },
  { id: 'ps-r304', bayNumber: 'R-304', zone: 'Zone B2 (Resident)', type: 'Resident', status: 'Occupied_Resident', currentVehiclePlate: 'ER-3390', assignedUnitNumber: 'B-304', occupantName: 'Elena Rostova' },
];

export const initialLPRDetections: LPRDetection[] = [
  {
    id: 'lpr-101',
    plateNumber: 'SJK-8821',
    confidence: 99.2,
    timestamp: 'Just now',
    cameraName: 'Gate 1 (Entry Cam)',
    matchedStatus: 'Resident_Approved',
    matchedUnit: 'A-101',
    matchedName: 'Sarah Jenkins (Resident)',
    suggestedAction: 'Auto_Open_Gate',
  },
  {
    id: 'lpr-102',
    plateNumber: 'LHM-4491',
    confidence: 97.8,
    timestamp: '2 mins ago',
    cameraName: 'Gate 1 (Entry Cam)',
    matchedStatus: 'PreRegistered_Guest',
    matchedUnit: 'A-101',
    matchedName: 'Liam Harrison (Guest of Sarah J.)',
    suggestedAction: 'Auto_Open_Gate',
  },
  {
    id: 'lpr-103',
    plateNumber: 'UNK-9941',
    confidence: 94.1,
    timestamp: '5 mins ago',
    cameraName: 'Gate 2 (Visitor Lane)',
    matchedStatus: 'Unknown_Vehicle',
    suggestedAction: 'Prompt_Guard_Verification',
  },
];
